export const UPDATE_USER_DATA = "UPDATE_USER_DATA";
export const UPDATE_USER_POSTS = "UPDATE_USER_POSTS";

export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAIL = "FETCH_USERS_FAIL";

export const FETCH_USER_POSTS_REQUEST = "FETCH_USER_POSTS_REQUEST";
export const FETCH_USER_POSTS_FAIL = "FETCH_USER_POSTS_FAIL";
